"""Type stubs for the Rust extension module."""

from typing import Any, Optional

__version__: str

class CoreError(Exception): ...

class Router:
    def __init__(
        self, models: list[str], strategy: str = "ordered", fallback_on: Optional[list[str]] = None
    ) -> None: ...
    def models(self) -> list[str]: ...
    def plan(self) -> list[str]: ...
    def ocr(self, request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
    async def aocr(self, request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
    def stats(self) -> dict[str, dict[str, Any]]: ...

def ocr(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
async def aocr(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
def list_models() -> list[str]: ...
def providers() -> list[dict[str, Any]]: ...
def pricing() -> dict[str, dict[str, Any]]: ...
def set_pricing(prices: dict[str, float]) -> None: ...
def reset_pricing() -> None: ...
def estimate_cost(model: str, pages: int) -> Optional[float]: ...
def resolve_model(model: str) -> str: ...
def score(
    prediction: str,
    truth: str,
    case_insensitive: bool = True,
    strip_markdown: bool = True,
    strip_punctuation: bool = False,
) -> dict[str, Any]: ...
def normalize_text(
    text: str, case_insensitive: bool = True, strip_markdown: bool = True, strip_punctuation: bool = False
) -> str: ...
def markdown_to_text(md: str) -> str: ...
def init_logging(level: str) -> None: ...
