"""Type stubs for the Rust extension module."""

from typing import Any, Optional

__version__: str

class CoreError(Exception): ...

class Router:
    def __init__(
        self,
        models: list[str],
        mode: str = "parse",
        strategy: str = "ordered",
        fallback_on: Optional[list[str]] = None,
    ) -> None: ...
    def models(self) -> list[str]: ...
    def mode(self) -> str: ...
    def plan(self) -> list[str]: ...
    def parse(self, request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
    async def aparse(self, request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
    def ocr(self, request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
    async def aocr(self, request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
    def extract(self, request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
    async def aextract(self, request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
    def stats(self) -> dict[str, dict[str, Any]]: ...

def parse(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
async def aparse(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
def ocr(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
async def aocr(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
def extract(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
async def aextract(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
def submit(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
async def asubmit(request: dict[str, Any], data: Optional[bytes] = None) -> dict[str, Any]: ...
def retrieve(job: dict[str, Any], options: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
async def aretrieve(job: dict[str, Any], options: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
def parse_webhook(model: str, payload: Any) -> dict[str, Any]: ...
def output_formats() -> list[str]: ...
def validate_output_format(format: str) -> str: ...
def render_parse(response: dict[str, Any], format: str) -> dict[str, Any]: ...
def render_extract(response: dict[str, Any], format: str) -> dict[str, Any]: ...
def list_models(mode: Optional[str] = None) -> list[str]: ...
def modes() -> list[str]: ...
def providers() -> list[dict[str, Any]]: ...
def pricing() -> dict[str, dict[str, Any]]: ...
def set_pricing(prices: dict[str, float], mode: str = "parse") -> None: ...
def reset_pricing() -> None: ...
def estimate_cost(model: str, mode: str, pages: int) -> Optional[float]: ...
def resolve_model(model: str, mode: Optional[str] = None) -> str: ...
def score(
    prediction: str,
    truth: str,
    case_insensitive: bool = True,
    strip_markdown: bool = True,
    strip_punctuation: bool = False,
) -> dict[str, Any]: ...
def normalize_text(
    text: str, case_insensitive: bool = True, strip_markdown: bool = True, strip_punctuation: bool = False
) -> str: ...
def markdown_to_text(md: str) -> str: ...
def init_logging(level: str) -> None: ...
