"""Generate THIRD_PARTY_NOTICES.md from `cargo metadata`.

Lists every crate that is compiled into a shipped artifact (the CLI binary and Docker image, the
Python wheel, the Node addon): the normal (non-dev) dependency closure of the workspace members,
on every target platform, so the list is a superset of what any one build links.

    python scripts/third_party_notices.py                 # rewrite THIRD_PARTY_NOTICES.md (summary)
    python scripts/third_party_notices.py --check         # exit 1 if the committed file is stale
    python scripts/third_party_notices.py --full OUT.txt  # summary + every crate's licence files

The summary is what the repository commits. `--full` collects each crate's own LICENSE / COPYING /
NOTICE files from the local cargo registry, i.e. the copyright and permission notices that MIT,
BSD, ISC, Apache-2.0 and similar licences ask binary redistributors to reproduce; attach it to
release artifacts. Standard library only.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_NOTICES.md"
LICENSE_FILE_PREFIXES = ("license", "licence", "copying", "notice", "unlicense", "copyright")

# Licences that would conflict with distributing MIT binaries if one were the *only* option.
COPYLEFT_MARKERS = ("GPL", "AGPL", "LGPL", "MPL", "EPL", "CDDL", "EUPL", "SSPL", "OSL")


def cargo_metadata() -> dict[str, Any]:
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return json.loads(out)


def shipped_packages(meta: dict[str, Any]) -> list[dict[str, Any]]:
    """Normal-dependency closure of the workspace members, excluding the members themselves."""
    packages = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    members = set(meta["workspace_members"])
    seen: set[str] = set()
    stack = list(members)
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        for dep in nodes[pid]["deps"]:
            if any(k["kind"] is None for k in dep["dep_kinds"]):
                stack.append(dep["pkg"])
    return sorted((packages[p] for p in seen - members), key=lambda p: (p["name"], p["version"]))


def only_copyleft(expr: str) -> bool:
    """True when no alternative of an SPDX-ish expression is free of copyleft markers."""
    alternatives = expr.replace("/", " OR ").split(" OR ")
    return all(any(m in alt for m in COPYLEFT_MARKERS) for alt in alternatives)


def render_summary(pkgs: list[dict[str, Any]]) -> str:
    by_license: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for p in pkgs:
        by_license[p.get("license") or "UNKNOWN (see crate)"].append(p)
    lines = [
        "# Third-party notices",
        "",
        "<!-- Generated by scripts/third_party_notices.py from Cargo.lock. Do not edit by hand. -->",
        "",
        "PuffinParse is MIT licensed (see [LICENSE](LICENSE)). The compiled artifacts (the `puffinparse`",
        "CLI and Docker image, the Python wheel and the Node addon) statically link the Rust crates",
        f"below: {len(pkgs)} crates, the normal-dependency closure of the workspace on every target.",
        "Each is used under the licence its authors chose; where a crate offers a choice, PuffinParse",
        "uses it under a permissive option (MIT, Apache-2.0, BSD, ISC, Zlib, Unicode-3.0, ...). No",
        "dependency is available only under a copyleft licence.",
        "",
        "The full copyright and licence texts of every crate are produced with",
        "`python scripts/third_party_notices.py --full THIRD_PARTY_LICENSES.txt`.",
        "",
        "Not linked, so not listed: the Python and Node packages have no runtime dependencies;",
        "`tesseract` (Apache-2.0) and `pdftoppm` (Poppler, GPL-2.0-or-later) are optional external",
        "programs the Tesseract provider runs as separate processes, found on `PATH` and never bundled;",
        "Docling and PaddleOCR are reached over HTTP. The Docker image's base layer",
        "(`gcr.io/distroless/cc-debian12`) carries its own Debian package licences (glibc, libgcc,",
        "CA certificates).",
        "",
        "Benchmark data and website assets are credited separately: see the Acknowledgements section",
        "of [README.md](README.md) and each `benchmark/datasets/*/README.md`.",
        "",
        "| Licence | Crates |",
        "|---|---:|",
    ]
    for lic in sorted(by_license, key=lambda k: (-len(by_license[k]), k)):
        lines.append(f"| `{lic}` | {len(by_license[lic])} |")
    for lic in sorted(by_license):
        lines += ["", f"## `{lic}`", ""]
        for p in by_license[lic]:
            repo = p.get("repository") or p.get("homepage") or f"https://crates.io/crates/{p['name']}"
            lines.append(f"- [{p['name']} {p['version']}]({repo})")
    return "\n".join(lines) + "\n"


def license_files(pkg: dict[str, Any]) -> list[Path]:
    crate_dir = Path(pkg["manifest_path"]).parent
    files = [
        f
        for f in sorted(crate_dir.iterdir())
        if f.is_file() and f.name.lower().startswith(LICENSE_FILE_PREFIXES)
    ]
    if pkg.get("license_file"):
        extra = crate_dir / pkg["license_file"]
        if extra.is_file() and extra not in files:
            files.append(extra)
    return files


def render_full(pkgs: list[dict[str, Any]]) -> str:
    parts = [render_summary(pkgs), "", "=" * 100, "Licence texts", "=" * 100]
    for p in pkgs:
        title = f"{p['name']} {p['version']}  ({p.get('license') or 'see files'})"
        parts += ["", "-" * 100, title, "-" * 100]
        files = license_files(p)
        if not files:
            parts.append(f"(no licence file shipped in the crate; licence: {p.get('license')})")
        for f in files:
            parts += [f"--- {f.name}", f.read_text(encoding="utf-8", errors="replace").rstrip()]
    return "\n".join(parts) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if THIRD_PARTY_NOTICES.md is out of date")
    ap.add_argument("--full", metavar="OUT", help="write summary plus every crate's licence files to OUT")
    args = ap.parse_args()

    pkgs = shipped_packages(cargo_metadata())
    bad = [p for p in pkgs if p.get("license") and only_copyleft(p["license"])]
    if bad:
        for p in bad:
            print(f"copyleft-only dependency: {p['name']} {p['version']} ({p['license']})", file=sys.stderr)
        return 1

    if args.full:
        Path(args.full).write_text(render_full(pkgs), encoding="utf-8")
        print(f"wrote {args.full} ({len(pkgs)} crates)")
        return 0
    summary = render_summary(pkgs)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != summary:
            print("THIRD_PARTY_NOTICES.md is stale: run scripts/third_party_notices.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(summary, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(pkgs)} crates)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
